import 'dart:math';

class LetterData {
  static const List<String> consonantOrder = [
    'ກ',
    'ງ',
    'ຂ',
    'ຈ',
    'ຄ',
    'ສ',
    'ຟ',
    'ດ',
    'ຝ',
    'ນ',
    'ປ',
    'ຣ',
    'ບ',
    'ລ',
    'ພ',
    'ວ',
    'ຕ',
    'ຊ',
    'ທ',
    'ມ',
    'ຖ',
    'ອ',
    'ຍ',
    'ຜ',
    'ຢ',
    'ຫ',
    'ຮ',
  ];

  static const List<String> placeholderConsonants = [
    'ກ',
    'ຈ',
    'ສ',
    'ດ',
    'ຕ',
    'ນ',
    'ບ',
    'ຟ',
    'ມ',
    'ລ',
  ];

  static String randomPlaceholder(Random random) {
    return placeholderConsonants[random.nextInt(placeholderConsonants.length)];
  }

  static const Map<String, String> lettersToWords = {
    'ກ': 'ໄກ່',
    'ຂ': 'ໄຂ່',
    'ຄ': 'ຄວາຍ',
    'ງ': 'ງົວ',
    'ຈ': 'ຈອກ',
    'ສ': 'ເສືອ',
    'ຊ': 'ຊ້າງ',
    'ຍ': 'ຍຸງ',
    'ດ': 'ເດັກ',
    'ຕ': 'ຕາ',
    'ຖ': 'ຖົງ',
    'ທ': 'ທຸງ',
    'ນ': 'ນົກ',
    'ບ': 'ແບ້',
    'ປ': 'ປາ',
    'ຜ': 'ເຜິ້ງ',
    'ຝ': 'ຝົນ',
    'ພ': 'ພູ',
    'ຟ': 'ໄຟ',
    'ມ': 'ແມວ',
    'ຢ': 'ຢາ',
    'ຣ': 'ຣະຄັງ',
    'ລ': 'ລີງ',
    'ວ': 'ວີ',
    'ຫ': 'ຫ່ານ',
    'ອ': 'ໂອ',
    'ຮ': 'ເຮືອ',
  };

  static const Map<String, String> laoToRomanization = {
    'ກ': 'ko',
    'ຂ': 'kho sung',
    'ຄ': 'kho tam',
    'ງ': 'ngo',
    'ຈ': 'co',
    'ສ': 'so sung',
    'ຊ': 'so tam',
    'ຍ': 'nyo',
    'ດ': 'do',
    'ຕ': 'to',
    'ຖ': 'tho sung',
    'ທ': 'tho tam',
    'ນ': 'no',
    'ບ': 'bo',
    'ປ': 'po',
    'ຜ': 'pho sung',
    'ຝ': 'fo tam',
    'ພ': 'pho tam',
    'ຟ': 'fo sung',
    'ມ': 'mo',
    'ຢ': 'yo',
    'ຣ': 'lo ling',
    'ລ': 'lo loot',
    'ວ': 'wo',
    'ຫ': 'ho sung',
    'ອ': 'o',
    'ຮ': 'ho tam',
  };

  static const Map<String, String> romanizationToLao = {
    "ko": "ກ",
    "kho sung": "ຂ",
    "kho tam": "ຄ",
    "ngo": "ງ",
    "co": "ຈ",
    "so sung": "ສ",
    "so tam": "ຊ",
    "nyo": "ຍ",
    "do": "ດ",
    "to": "ຕ",
    "tho sung": "ຖ",
    "tho tam": "ທ",
    "no": "ນ",
    "bo": "ບ",
    "po": "ປ",
    "pho sung": "ຜ",
    "fo tam": "ຝ",
    "pho tam": "ພ",
    "fo sung": "ຟ",
    "mo": "ມ",
    "yo": "ຢ",
    "lo ling": "ຣ",
    "lo loot": "ລ",
    "wo": "ວ",
    "ho sung": "ຫ",
    "o": "ອ",
    "ho tam": "ຮ",
  };

  static const String vowelPlaceholder = '◌';

  static const Map<String, String> vowelVariations = {
    'ເ◌ຍ': '◌ຽ',
    '◌ະ': '◌ັ',
    'ແ◌ະ': 'ແ◌ັ',
    'ໂ◌ະ': '◌ົ',
    'ເ◌າະ': '◌ັອ',
  };

  static int getVowelIndex(String vowel) {
    final int index = vowelsIndex.indexOf(vowel);
    if (index == -1) {
      return vowelsIndex.indexOf(
        vowelVariations.keys.firstWhere((key) => vowelVariations[key] == vowel),
      );
    } else {
      return index;
    }
  }

  static const List<String> vowelsIndex = [
    '◌ະ',
    '◌າ',
    '◌ິ',
    '◌ີ',
    '◌ຶ',
    '◌ື',
    '◌ຸ',
    '◌ູ',
    'ເ◌ະ',
    'ເ◌',
    'ແ◌ະ',
    'ແ◌',
    'ໂ◌ະ',
    'ໂ◌',
    'ເ◌າະ',
    '◌ໍ',
    'ເ◌ິ',
    'ເ◌ີ',
    'ເ◌ຍ',
    'ເ◌ືອ',
    '◌ົວ',
    'ໄ◌',
    'ໃ◌',
    'ເ◌ົາ',
    '◌ຳ',
    '◌ອຍ',
    '◌ວຍ',
  ];

  static const List<String> vowelTeachingOrder = [
    'ເ◌ຍ',
    'ເ◌ືອ',
    '◌ົວ',
    'ໄ◌',
    'ໃ◌',
    'ເ◌ົາ',
    '◌ຳ',
    '◌ອຍ',
    '◌ວຍ',
    '◌ິ',
    '◌ີ',
    '◌ຶ',
    '◌ື',
    '◌ຸ',
    '◌ູ',
    'ເ◌ິ',
    'ເ◌ີ',
    '◌ະ, ◌ັ',
    '◌າ',
    'ເ◌ະ',
    'ເ◌',
    'ແ◌ະ, ແ◌ັ',
    'ແ◌',
    'ໂ◌ະ, ◌ົ',
    'ໂ◌',
    'ເ◌າະ, ◌ັອ',
    '◌ໍ',
  ];
}
